name: Upload SQL Files to Azure Synapse

on:
  push:
    branches:
      - main

jobs:
  upload-sql-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Azure PowerShell
        uses: azure/setup-azurerm@v1

      - name: Install Azure PowerShell module
        run: Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser

      - name: Upload SQL Files to Azure Synapse
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          STORAGE_ACCOUNT_NAME: satyadldemo
          CONTAINER_NAME: satyadlfs
        run: |
          $localFolderPath = "C:\Users\Satyakumar_Surisetti\Documents\sqlfiles"

          Connect-AzAccount -ServicePrincipal -Credential (New-Object PSCredential -ArgumentList $env:AZURE_CLIENT_ID, (ConvertTo-SecureString -String $env:AZURE_CLIENT_SECRET -AsPlainText -Force)) -Tenant $env:AZURE_TENANT_ID

          $context = Get-AzStorageAccountKey -ResourceGroupName "your_resource_group_name" -AccountName $env:STORAGE_ACCOUNT_NAME | Select-Object -ExpandProperty Context

          Get-ChildItem -Path $localFolderPath -Recurse | ForEach-Object {
              $blobPath = $_.FullName.Replace($localFolderPath, "").TrimStart("\")
              $blobName = $_.Name
              Set-AzStorageBlobContent -Container $env:CONTAINER_NAME -File $_.FullName -Blob "$blobPath/$blobName" -Context $context
          }
