name: Upload SQL Files to Azure Synapse

on:
  push:
    branches:
      - main

jobs:
  upload-sql-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure PowerShell module
        run: |
          pwsh -Command "Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser"

      - name: Upload SQL Files to Azure Synapse
        env:
          AZURE_STORAGE_ACCOUNT: satyadldemo
          AZURE_STORAGE_KEY: "qfzI4S8ydhvdIGLrNLAAOhD735FpbQCmzuUMCHzId9Te4n9gR+FVyDWBB9o7GZKMl66UyPB5l8Tj+AStzjTewA=="
          CONTAINER_NAME: satyadlfs
        run: |
          $localFolderPath = "/sqlfiles"
          $context = New-AzStorageContext -StorageAccountName $env:AZURE_STORAGE_ACCOUNT -StorageAccountKey $env:AZURE_STORAGE_KEY

          Get-ChildItem -Path $localFolderPath -Recurse | ForEach-Object {
          $blobPath = $_.FullName.Replace($localFolderPath, "").TrimStart("/")
          $blobName = $_.Name
          Set-AzStorageBlobContent -Container $env:CONTAINER_NAME -File $_.FullName -Blob "$blobPath/$blobName" -Context $context
          }

